### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by PolskiStevek** [PolskiStevek/ServerControl#2]
[15:11:13] [Server thread/ERROR]: Could not pass event PlayerChatEvent to ServerControl vBUILD3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection$8.evaluate(PlayerConnection.java:1120) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at Class_Cmds.a(Class_Cmds.java:42) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	... 11 more

**Comment by PolskiStevek** [comment]
https://github.com/PolskiStevek/ServerControl/commit/30cf5776d86d31cbb9c83c124063fa0326207588
Should be fixed now, but not tested.
